### ISSUE TITLE
Some errors when editing expanded snippets

### ISSUE THREAD

**Issue by haorenW1025** [archseer/snippets.nvim#1]
I've got some errors when editing snippets, my testing init.vim is as follow
```vim
set runtimepath+=~/.vim/plugged/snippets.nvim
lua vim.snippet = require 'snippet'

" map <c-l> to expanding snippet under the cursor
imap <c-l> <cmd>lua require'snippet'.expand_at_cursor()<CR>
```
When I type for and then `<c-l>` and expanding the snippets, the snippets expansion works perfectly, but I'll get this error when I'm trying to type something after that
```
E5108: Error executing lua ....vim/plugged/snippets.nvim/lua/snippet/init.lua:415: attempt to index a nil value
```
And then since the `insertCharPre` autocmd is activated, I'll get this error whenever I tried to type again
```
E5108: Error executing lua .../.vim/plugged/snippets.nvim/lua/snippet/init.lua:514: attempt to call field 'text' (a string value)
```

**Comment by archseer** [comment]
https://github.com/archseer/snippets.nvim/commit/f8eb129 should be a workaround for now, I'll reimplement mirroring/syncing tabstops later

**Comment by haorenW1025** [comment]
Tested it, works fine now! Close this for now.
